# Generated by Django 4.0.4 on 2022-06-07 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='bio',
            name='bio',
            field=models.CharField(max_length=10000),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(default=' ', max_length=5000)),
                ('brand', models.CharField(default=' ', max_length=2000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.people')),
            ],
        ),
    ]
